// # Copyright (c) ZStack.io, Inc.

package test

import (
	"fmt"
	"testing"
	"time"

	"github.com/kataras/golog"

	"github.com/terraform-zstack-modules/zsphere-sdk-go/pkg/param"
)

func TestQueryAccessKeys(t *testing.T) {
	queryParam := param.NewQueryParam()
	accessKeys, err := accountLoginCli.QueryAccessKeys(queryParam)
	if err != nil {
		t.Errorf("TestQueryAccessKeys err %v", err)
		return
	}
	golog.Infof("Query access keys result: %v", accessKeys)
}

func TestCreateGetDeleteAccessKeyFlow(t *testing.T) {
	// Ensure we have a logged-in client and obtain account & user UUIDs
	sess, err := accountLoginCli.Login()
	if err != nil {
		t.Fatalf("Login error: %v", err)
	}
	defer accountLoginCli.Logout()
	// sess contains AccountUuid and UserUuid for the currently logged-in session

	// Build a unique AccessKeyID so that repeated test runs don't collide
	accessKeyID := fmt.Sprintf("go-sdk-test-%d", time.Now().Unix())

	createParam := param.CreateAccessKeyParam{
		BaseParam: param.BaseParam{},
		Params: param.CreateAccessKeyDetailParams{
			AccountUUID: sess.AccountUuid,
			UserUUID:    sess.UserUuid,
			Description: nil,
			AccessKeyID: &accessKeyID,
			// AccessKeySecret can be generated by ZStack when nil
		},
	}

	// Create the access key
	resp, err := accountLoginCli.CreateAccessKey(&createParam)
	if err != nil {
		t.Fatalf("CreateAccessKey error: %v", err)
	}
	if resp == nil {
		t.Fatalf("CreateAccessKey returned nil response")
	}
	golog.Infof("Created access key: %v", resp)

	// Try to get the access key by UUID
	getResp, err := accountLoginCli.GetAccessKey(resp.UUID)
	if err != nil {
		t.Fatalf("GetAccessKey error: %v", err)
	}
	golog.Infof("Get access key: %v", getResp)

	// Delete the access key
	/*
		err = accountLoginCli.DeleteAccessKey(resp.UUID, param.DeleteModePermissive)
		if err != nil {
			t.Errorf("DeleteAccessKey error: %v", err)
			// don't return right away; we may still want to check deletion or proceed to cleanup in other tests
		}
	*/

	// Optionally verify that querying with the accessKeyID returns none or not; skipping strict assertion for environment variance
}
